version: '2'
services:
  chrome-flow:
     image: selenium/standalone-chrome:latest
     container_name: chrome-flow
     shm_size: 2g
     restart: always

  come-in-flow:
     build:
       context: .
       dockerfile: ./Dockerfile
     image: popularize:5
     container_name: come-in-flow
     environment:
        popularize_access_token: 68518eaa2d7012fc0bf9e0bb0eea9466090c7ef5547423f0ef4c537ea77b376e
        popularize_keyword: www.cyzxs.cn=橙游,橙游资讯,橙游官网,橙游app|www.yingmuzhi.cn=婴母知,婴母知官网,婴母知app,婴母知资讯
     restart: always
     command: python3.7  /code/scan_mian.py